// <auto-generated />
using System;
using Bonheur.Outlets.Dataservice.EntityData.Outlets;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bonheur.Outlets.Dataservice.Migrations.Outlets
{
    [DbContext(typeof(OutletsContext))]
    [Migration("20230918132801_OutletsMigration")]
    partial class OutletsMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");

            modelBuilder.Entity("Bonheur.Outlets.Dataservice.EntityData.Outlets.Models.Shop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ConnectionString")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Connection_String");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("PhoneNo")
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("Phone_no");

                    b.Property<string>("ShopName")
                        .IsRequired()
                        .HasMaxLength(110)
                        .HasColumnType("varchar(110)")
                        .HasColumnName("Shop_Name");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("shops", (string)null);
                });

            modelBuilder.Entity("Bonheur.Outlets.Dataservice.EntityData.Outlets.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Name")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<byte[]>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("varbinary(255)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasMaxLength(255)
                        .HasColumnType("varbinary(255)");

                    b.Property<string>("PhoneNo")
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("Phone_No");

                    b.Property<int>("ShopId")
                        .HasColumnType("int")
                        .HasColumnName("Shop_Id");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ShopId" }, "FK_Users_Shops_ShopId_idx");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Bonheur.Outlets.Dataservice.EntityData.Outlets.Models.User", b =>
                {
                    b.HasOne("Bonheur.Outlets.Dataservice.EntityData.Outlets.Models.Shop", "Shop")
                        .WithMany("Users")
                        .HasForeignKey("ShopId")
                        .IsRequired()
                        .HasConstraintName("FK_Users_Shops_ShopId");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("Bonheur.Outlets.Dataservice.EntityData.Outlets.Models.Shop", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
